#pragma once

#include <cstdint>

enum EAppType : unsigned int
{
	APPTYPE_INVALID = 0x0,
	APPTYPE_GAME = 0x1,
	APPTYPE_APPLICATION = 0x2,
	APPTYPE_TOOL = 0x4,
	APPTYPE_DEMO = 0x8,
	APPTYPE_MEDIA = 0x10,
	APPTYPE_DLC = 0x20,
	APPTYPE_GUIDE = 0x40,
	APPTYPE_DRIVER = 0x80,
	APPTYPE_CONFIG = 0x100,
	APPTYPE_HARDWARE = 0x200,
	APPTYPE_FRANCHISE = 0x400,
	APPTYPE_VIDEO = 0x800,
	APPTYPE_PLUGIN = 0x1000,
	APPTYPE_MUSIC = 0x2000,
	APPTYPE_SERIES = 0x4000,
	APPTYPE_COMIC = 0x8000,
	APPTYPE_BETA = 0x10000,
	APPTYPE_SHORTCUT = 0x40000000,
	APPTYPE_DEPOTONLY = -0x80000000, //???
};

enum EAppInfoSection
{
	APPINFOSECTION_ALL = 0x1,
	APPINFOSECTION_COMMON = 0x2,
	APPINFOSECTION_EXTENDED = 0x3,
	APPINFOSECTION_CONFIG = 0x4,
	APPINFOSECTION_STATS = 0x5,
	APPINFOSECTION_INSTALL = 0x6,
	APPINFOSECTION_DEPOTS = 0x7,
	APPINFOSECTION_VAC = 0x8,
	APPINFOSECTION_DRM = 0x9,
	APPINFOSECTION_UFS = 0xa,
	APPINFOSECTION_OGG = 0xb,
	APPINFOSECTION_ITEMS = 0xc,
	APPINFOSECTION_POLICIES = 0xd,
	APPINFOSECTION_SYSREQS = 0xe,
	APPINFOSECTION_COMMUNITY = 0xf,
	APPINFOSECTION_STORE = 0x10,
	APPINFOSECTION_LOCALIZATION = 0x11,
	APPINFOSECTION_BROADCASTGAMEDATA = 0x12,
	APPINFOSECTION_COMPUTED = 0x13,
	APPINFOSECTION_ALBUMMETADATA = 0x14,
	APPINFOSECTION_UNKNOWN = 0x15,
};

class IClientApps
{
public:
	int32_t getAppData(uint32_t appId, const char* name, const char* pChOut, uint32_t outSize);
	uint32_t getAppDataSection(uint32_t appId, EAppInfoSection section, const char* pChOut, uint32_t outSize);
	bool requestAppInfoUpdate(uint32_t* appIds, uint32_t numAppIds);
	EAppType getAppType(uint32_t appId);
};

extern IClientApps* g_pClientApps;
