// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content_manifest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_content_5fmanifest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_content_5fmanifest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_content_5fmanifest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_content_5fmanifest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class CContentServerDirectory_GetManifestRequestCode_Request;
struct CContentServerDirectory_GetManifestRequestCode_RequestDefaultTypeInternal;
extern CContentServerDirectory_GetManifestRequestCode_RequestDefaultTypeInternal _CContentServerDirectory_GetManifestRequestCode_Request_default_instance_;
class CContentServerDirectory_GetManifestRequestCode_Response;
struct CContentServerDirectory_GetManifestRequestCode_ResponseDefaultTypeInternal;
extern CContentServerDirectory_GetManifestRequestCode_ResponseDefaultTypeInternal _CContentServerDirectory_GetManifestRequestCode_Response_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CContentServerDirectory_GetManifestRequestCode_Request* Arena::CreateMaybeMessage<::CContentServerDirectory_GetManifestRequestCode_Request>(Arena*);
template<> ::CContentServerDirectory_GetManifestRequestCode_Response* Arena::CreateMaybeMessage<::CContentServerDirectory_GetManifestRequestCode_Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CContentServerDirectory_GetManifestRequestCode_Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CContentServerDirectory_GetManifestRequestCode_Request) */ {
 public:
  inline CContentServerDirectory_GetManifestRequestCode_Request() : CContentServerDirectory_GetManifestRequestCode_Request(nullptr) {}
  virtual ~CContentServerDirectory_GetManifestRequestCode_Request();
  explicit constexpr CContentServerDirectory_GetManifestRequestCode_Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CContentServerDirectory_GetManifestRequestCode_Request(const CContentServerDirectory_GetManifestRequestCode_Request& from);
  CContentServerDirectory_GetManifestRequestCode_Request(CContentServerDirectory_GetManifestRequestCode_Request&& from) noexcept
    : CContentServerDirectory_GetManifestRequestCode_Request() {
    *this = ::std::move(from);
  }

  inline CContentServerDirectory_GetManifestRequestCode_Request& operator=(const CContentServerDirectory_GetManifestRequestCode_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline CContentServerDirectory_GetManifestRequestCode_Request& operator=(CContentServerDirectory_GetManifestRequestCode_Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CContentServerDirectory_GetManifestRequestCode_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const CContentServerDirectory_GetManifestRequestCode_Request* internal_default_instance() {
    return reinterpret_cast<const CContentServerDirectory_GetManifestRequestCode_Request*>(
               &_CContentServerDirectory_GetManifestRequestCode_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CContentServerDirectory_GetManifestRequestCode_Request& a, CContentServerDirectory_GetManifestRequestCode_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(CContentServerDirectory_GetManifestRequestCode_Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CContentServerDirectory_GetManifestRequestCode_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CContentServerDirectory_GetManifestRequestCode_Request* New() const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Request>(nullptr);
  }

  CContentServerDirectory_GetManifestRequestCode_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Request>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CContentServerDirectory_GetManifestRequestCode_Request& from);
  void MergeFrom(const CContentServerDirectory_GetManifestRequestCode_Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CContentServerDirectory_GetManifestRequestCode_Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CContentServerDirectory_GetManifestRequestCode_Request";
  }
  protected:
  explicit CContentServerDirectory_GetManifestRequestCode_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppBranchFieldNumber = 4,
    kBranchPasswordHashFieldNumber = 5,
    kAppIdFieldNumber = 1,
    kDepotIdFieldNumber = 2,
    kManifestIdFieldNumber = 3,
  };
  // optional string app_branch = 4;
  bool has_app_branch() const;
  private:
  bool _internal_has_app_branch() const;
  public:
  void clear_app_branch();
  const std::string& app_branch() const;
  void set_app_branch(const std::string& value);
  void set_app_branch(std::string&& value);
  void set_app_branch(const char* value);
  void set_app_branch(const char* value, size_t size);
  std::string* mutable_app_branch();
  std::string* release_app_branch();
  void set_allocated_app_branch(std::string* app_branch);
  private:
  const std::string& _internal_app_branch() const;
  void _internal_set_app_branch(const std::string& value);
  std::string* _internal_mutable_app_branch();
  public:

  // optional string branch_password_hash = 5;
  bool has_branch_password_hash() const;
  private:
  bool _internal_has_branch_password_hash() const;
  public:
  void clear_branch_password_hash();
  const std::string& branch_password_hash() const;
  void set_branch_password_hash(const std::string& value);
  void set_branch_password_hash(std::string&& value);
  void set_branch_password_hash(const char* value);
  void set_branch_password_hash(const char* value, size_t size);
  std::string* mutable_branch_password_hash();
  std::string* release_branch_password_hash();
  void set_allocated_branch_password_hash(std::string* branch_password_hash);
  private:
  const std::string& _internal_branch_password_hash() const;
  void _internal_set_branch_password_hash(const std::string& value);
  std::string* _internal_mutable_branch_password_hash();
  public:

  // optional uint32 app_id = 1;
  bool has_app_id() const;
  private:
  bool _internal_has_app_id() const;
  public:
  void clear_app_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 app_id() const;
  void set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_app_id() const;
  void _internal_set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 depot_id = 2;
  bool has_depot_id() const;
  private:
  bool _internal_has_depot_id() const;
  public:
  void clear_depot_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 depot_id() const;
  void set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_depot_id() const;
  void _internal_set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint64 manifest_id = 3;
  bool has_manifest_id() const;
  private:
  bool _internal_has_manifest_id() const;
  public:
  void clear_manifest_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_id() const;
  void set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_manifest_id() const;
  void _internal_set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:CContentServerDirectory_GetManifestRequestCode_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_branch_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr branch_password_hash_;
  ::PROTOBUF_NAMESPACE_ID::uint32 app_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 depot_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_id_;
  friend struct ::TableStruct_content_5fmanifest_2eproto;
};
// -------------------------------------------------------------------

class CContentServerDirectory_GetManifestRequestCode_Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CContentServerDirectory_GetManifestRequestCode_Response) */ {
 public:
  inline CContentServerDirectory_GetManifestRequestCode_Response() : CContentServerDirectory_GetManifestRequestCode_Response(nullptr) {}
  virtual ~CContentServerDirectory_GetManifestRequestCode_Response();
  explicit constexpr CContentServerDirectory_GetManifestRequestCode_Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CContentServerDirectory_GetManifestRequestCode_Response(const CContentServerDirectory_GetManifestRequestCode_Response& from);
  CContentServerDirectory_GetManifestRequestCode_Response(CContentServerDirectory_GetManifestRequestCode_Response&& from) noexcept
    : CContentServerDirectory_GetManifestRequestCode_Response() {
    *this = ::std::move(from);
  }

  inline CContentServerDirectory_GetManifestRequestCode_Response& operator=(const CContentServerDirectory_GetManifestRequestCode_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline CContentServerDirectory_GetManifestRequestCode_Response& operator=(CContentServerDirectory_GetManifestRequestCode_Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CContentServerDirectory_GetManifestRequestCode_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const CContentServerDirectory_GetManifestRequestCode_Response* internal_default_instance() {
    return reinterpret_cast<const CContentServerDirectory_GetManifestRequestCode_Response*>(
               &_CContentServerDirectory_GetManifestRequestCode_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CContentServerDirectory_GetManifestRequestCode_Response& a, CContentServerDirectory_GetManifestRequestCode_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(CContentServerDirectory_GetManifestRequestCode_Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CContentServerDirectory_GetManifestRequestCode_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CContentServerDirectory_GetManifestRequestCode_Response* New() const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Response>(nullptr);
  }

  CContentServerDirectory_GetManifestRequestCode_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Response>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CContentServerDirectory_GetManifestRequestCode_Response& from);
  void MergeFrom(const CContentServerDirectory_GetManifestRequestCode_Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CContentServerDirectory_GetManifestRequestCode_Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CContentServerDirectory_GetManifestRequestCode_Response";
  }
  protected:
  explicit CContentServerDirectory_GetManifestRequestCode_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kManifestRequestCodeFieldNumber = 1,
  };
  // optional uint64 manifest_request_code = 1;
  bool has_manifest_request_code() const;
  private:
  bool _internal_has_manifest_request_code() const;
  public:
  void clear_manifest_request_code();
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_request_code() const;
  void set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_manifest_request_code() const;
  void _internal_set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:CContentServerDirectory_GetManifestRequestCode_Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_request_code_;
  friend struct ::TableStruct_content_5fmanifest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CContentServerDirectory_GetManifestRequestCode_Request

// optional uint32 app_id = 1;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_app_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_app_id() const {
  return _internal_has_app_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_app_id() {
  app_id_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::_internal_app_id() const {
  return app_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::app_id() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.app_id)
  return _internal_app_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  app_id_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_app_id(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.app_id)
}

// optional uint32 depot_id = 2;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_depot_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_depot_id() const {
  return _internal_has_depot_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_depot_id() {
  depot_id_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::_internal_depot_id() const {
  return depot_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::depot_id() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.depot_id)
  return _internal_depot_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  depot_id_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_depot_id(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.depot_id)
}

// optional uint64 manifest_id = 3;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_manifest_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_manifest_id() const {
  return _internal_has_manifest_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_manifest_id() {
  manifest_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Request::_internal_manifest_id() const {
  return manifest_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Request::manifest_id() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.manifest_id)
  return _internal_manifest_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  manifest_id_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_manifest_id(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.manifest_id)
}

// optional string app_branch = 4;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_app_branch() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_app_branch() const {
  return _internal_has_app_branch();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_app_branch() {
  app_branch_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::app_branch() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
  return _internal_app_branch();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(const std::string& value) {
  _internal_set_app_branch(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::mutable_app_branch() {
  // @@protoc_insertion_point(field_mutable:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
  return _internal_mutable_app_branch();
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::_internal_app_branch() const {
  return app_branch_.Get();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_app_branch(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::_internal_mutable_app_branch() {
  _has_bits_[0] |= 0x00000001u;
  return app_branch_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::release_app_branch() {
  // @@protoc_insertion_point(field_release:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
  if (!_internal_has_app_branch()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return app_branch_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_allocated_app_branch(std::string* app_branch) {
  if (app_branch != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  app_branch_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app_branch,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}

// optional string branch_password_hash = 5;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_branch_password_hash() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_branch_password_hash() const {
  return _internal_has_branch_password_hash();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_branch_password_hash() {
  branch_password_hash_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::branch_password_hash() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
  return _internal_branch_password_hash();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(const std::string& value) {
  _internal_set_branch_password_hash(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::mutable_branch_password_hash() {
  // @@protoc_insertion_point(field_mutable:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
  return _internal_mutable_branch_password_hash();
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::_internal_branch_password_hash() const {
  return branch_password_hash_.Get();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_branch_password_hash(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::_internal_mutable_branch_password_hash() {
  _has_bits_[0] |= 0x00000002u;
  return branch_password_hash_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::release_branch_password_hash() {
  // @@protoc_insertion_point(field_release:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
  if (!_internal_has_branch_password_hash()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return branch_password_hash_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_allocated_branch_password_hash(std::string* branch_password_hash) {
  if (branch_password_hash != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  branch_password_hash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), branch_password_hash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}

// -------------------------------------------------------------------

// CContentServerDirectory_GetManifestRequestCode_Response

// optional uint64 manifest_request_code = 1;
inline bool CContentServerDirectory_GetManifestRequestCode_Response::_internal_has_manifest_request_code() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Response::has_manifest_request_code() const {
  return _internal_has_manifest_request_code();
}
inline void CContentServerDirectory_GetManifestRequestCode_Response::clear_manifest_request_code() {
  manifest_request_code_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Response::_internal_manifest_request_code() const {
  return manifest_request_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Response::manifest_request_code() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Response.manifest_request_code)
  return _internal_manifest_request_code();
}
inline void CContentServerDirectory_GetManifestRequestCode_Response::_internal_set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  manifest_request_code_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Response::set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_manifest_request_code(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Response.manifest_request_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_content_5fmanifest_2eproto
