// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_unified_base.steamclient.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_steammessages_5funified_5fbase_2esteamclient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_steammessages_5funified_5fbase_2esteamclient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_steammessages_5funified_5fbase_2esteamclient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5funified_5fbase_2esteamclient_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class NoResponse;
struct NoResponseDefaultTypeInternal;
extern NoResponseDefaultTypeInternal _NoResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::NoResponse* Arena::CreateMaybeMessage<::NoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum EProtoExecutionSite : int {
  k_EProtoExecutionSiteUnknown = 0,
  k_EProtoExecutionSiteSteamClient = 2
};
bool EProtoExecutionSite_IsValid(int value);
constexpr EProtoExecutionSite EProtoExecutionSite_MIN = k_EProtoExecutionSiteUnknown;
constexpr EProtoExecutionSite EProtoExecutionSite_MAX = k_EProtoExecutionSiteSteamClient;
constexpr int EProtoExecutionSite_ARRAYSIZE = EProtoExecutionSite_MAX + 1;

const std::string& EProtoExecutionSite_Name(EProtoExecutionSite value);
template<typename T>
inline const std::string& EProtoExecutionSite_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EProtoExecutionSite>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EProtoExecutionSite_Name.");
  return EProtoExecutionSite_Name(static_cast<EProtoExecutionSite>(enum_t_value));
}
bool EProtoExecutionSite_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EProtoExecutionSite* value);
enum EProtoServiceType : int {
  k_EProtoServiceTypeSteamMessages = 0,
  k_EProtoServiceTypeVRGamepadUIMessages = 1
};
bool EProtoServiceType_IsValid(int value);
constexpr EProtoServiceType EProtoServiceType_MIN = k_EProtoServiceTypeSteamMessages;
constexpr EProtoServiceType EProtoServiceType_MAX = k_EProtoServiceTypeVRGamepadUIMessages;
constexpr int EProtoServiceType_ARRAYSIZE = EProtoServiceType_MAX + 1;

const std::string& EProtoServiceType_Name(EProtoServiceType value);
template<typename T>
inline const std::string& EProtoServiceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EProtoServiceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EProtoServiceType_Name.");
  return EProtoServiceType_Name(static_cast<EProtoServiceType>(enum_t_value));
}
bool EProtoServiceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EProtoServiceType* value);
// ===================================================================

class NoResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:NoResponse) */ {
 public:
  inline NoResponse() : NoResponse(nullptr) {}
  virtual ~NoResponse();
  explicit constexpr NoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NoResponse(const NoResponse& from);
  NoResponse(NoResponse&& from) noexcept
    : NoResponse() {
    *this = ::std::move(from);
  }

  inline NoResponse& operator=(const NoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline NoResponse& operator=(NoResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const NoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const NoResponse* internal_default_instance() {
    return reinterpret_cast<const NoResponse*>(
               &_NoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NoResponse& a, NoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(NoResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NoResponse* New() const final {
    return CreateMaybeMessage<NoResponse>(nullptr);
  }

  NoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NoResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const NoResponse& from);
  void MergeFrom(const NoResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NoResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NoResponse";
  }
  protected:
  explicit NoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:NoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_steammessages_5funified_5fbase_2esteamclient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NoResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::EProtoExecutionSite> : ::std::true_type {};
template <> struct is_proto_enum< ::EProtoServiceType> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_steammessages_5funified_5fbase_2esteamclient_2eproto
