// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_unified_base.steamclient.proto

#include "steammessages_unified_base.steamclient.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr NoResponse::NoResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct NoResponseDefaultTypeInternal {
  constexpr NoResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NoResponseDefaultTypeInternal() {}
  union {
    NoResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NoResponseDefaultTypeInternal _NoResponse_default_instance_;
bool EProtoExecutionSite_IsValid(int value) {
  switch (value) {
    case 0:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> EProtoExecutionSite_strings[2] = {};

static const char EProtoExecutionSite_names[] =
  "k_EProtoExecutionSiteSteamClient"
  "k_EProtoExecutionSiteUnknown";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry EProtoExecutionSite_entries[] = {
  { {EProtoExecutionSite_names + 0, 32}, 2 },
  { {EProtoExecutionSite_names + 32, 28}, 0 },
};

static const int EProtoExecutionSite_entries_by_number[] = {
  1, // 0 -> k_EProtoExecutionSiteUnknown
  0, // 2 -> k_EProtoExecutionSiteSteamClient
};

const std::string& EProtoExecutionSite_Name(
    EProtoExecutionSite value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          EProtoExecutionSite_entries,
          EProtoExecutionSite_entries_by_number,
          2, EProtoExecutionSite_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      EProtoExecutionSite_entries,
      EProtoExecutionSite_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     EProtoExecutionSite_strings[idx].get();
}
bool EProtoExecutionSite_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EProtoExecutionSite* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      EProtoExecutionSite_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<EProtoExecutionSite>(int_value);
  }
  return success;
}
bool EProtoServiceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> EProtoServiceType_strings[2] = {};

static const char EProtoServiceType_names[] =
  "k_EProtoServiceTypeSteamMessages"
  "k_EProtoServiceTypeVRGamepadUIMessages";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry EProtoServiceType_entries[] = {
  { {EProtoServiceType_names + 0, 32}, 0 },
  { {EProtoServiceType_names + 32, 38}, 1 },
};

static const int EProtoServiceType_entries_by_number[] = {
  0, // 0 -> k_EProtoServiceTypeSteamMessages
  1, // 1 -> k_EProtoServiceTypeVRGamepadUIMessages
};

const std::string& EProtoServiceType_Name(
    EProtoServiceType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          EProtoServiceType_entries,
          EProtoServiceType_entries_by_number,
          2, EProtoServiceType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      EProtoServiceType_entries,
      EProtoServiceType_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     EProtoServiceType_strings[idx].get();
}
bool EProtoServiceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EProtoServiceType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      EProtoServiceType_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<EProtoServiceType>(int_value);
  }
  return success;
}

// ===================================================================

class NoResponse::_Internal {
 public:
};

NoResponse::NoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NoResponse)
}
NoResponse::NoResponse(const NoResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:NoResponse)
}

void NoResponse::SharedCtor() {
}

NoResponse::~NoResponse() {
  // @@protoc_insertion_point(destructor:NoResponse)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void NoResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void NoResponse::ArenaDtor(void* object) {
  NoResponse* _this = reinterpret_cast< NoResponse* >(object);
  (void)_this;
}
void NoResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NoResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:NoResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* NoResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NoResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NoResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NoResponse)
  return target;
}

size_t NoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NoResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NoResponse::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const NoResponse*>(
      &from));
}

void NoResponse::MergeFrom(const NoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void NoResponse::CopyFrom(const NoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NoResponse::IsInitialized() const {
  return true;
}

void NoResponse::InternalSwap(NoResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
}

std::string NoResponse::GetTypeName() const {
  return "NoResponse";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::NoResponse* Arena::CreateMaybeMessage< ::NoResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NoResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
